source 'https://github.com/CocoaPods/Specs.git'
target 'TripKey2' do
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'

use_frameworks!

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'


end
